Time stamp
Software-Management-HSBI/Java-Client pull request #33
Opened 2024-01-10 09:03 UTC by MatteoXAntoz

2024-01-10 19:21 UTC, Minerder requested changes
Sieht gut aus! Habe aber noch ein paar Ergänzungen und bitte gewöhn dir an spotless laufen zu lassen

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Constants.java
> +    //3 Multiplayerr
Kann gelöscht werden

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Game.java
> +double bounce;
``bounce`` wird nur ein mal in der Methode ``renderSinglePlayer()`` benutzt also könnte man die Berechnung vom ``bounce`` aus der Methode ``updateSinglePlayer()`` in ``renderSinglePlayer()`` tun. Dadurch muss bounce auch nicht mehr global sein

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Game.java
> +         // Here will be played all sounds
Kommentar bitte ändern

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Game.java
> +            DrawTexture(texture, player.x, (int) (player.y+bounce), WHITE);
``bounce`` zu einem int machen damit man hier das casten weg machen kann

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +        } else if (round > 1) {
Hier kann die if Bedingung gelöscht werden.

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +        msMax = Math.max(msMax, ms);
Die drei Variablen werden nur hier benutzt und können gelöscht werden

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +    boolean isColliding() {
Wenn ich es richtig verstanden hab wird hier geprüft ob der Spieler mit der Start/Finish Line kollidiert. Der Methodenname ist etwas verwirrend und sollte geändert werden. Ich würde vorschlagen isPlayerOnFinish

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +        Raylib.Color childenColor = Util.color(255, 255, 255, (int) (0.6 * 255));
Unused

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +        prevTime = startTime;
Können auch auf 0 gesetzt werden. Macht kein Unterschied

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +            fpsMax = Math.max(fpsMax, fps);
Beide Variablen haben keinen nutzen und können gelöscht werden

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Stats.java
> +    private long startTime;
Ich sehe keinen nutzen für diese Variable

2024-01-10 19:21 UTC, edwindik commented on app/src/main/java/Game.java
> +       // sounds.add(new Sound(Constants.SOUNDSPATH,"racer"));
Glaube das sollte nicht auskommentiert bleiben

2024-01-10 19:21 UTC, Minerder commented on app/src/main/java/Stats.java
> +        startTime = end();
Den Inhalt der Methode ``end()`` kann hier eingesetzt werden. Es gibt keinen Grund den Code auszulagern

2024-01-10 19:23 UTC, Minerder commented
Ich habe bemerkt das die Startlinie auch als Ziellinie benutzt wird aber ist der schwarze streifen nicht als Ziellinie gedacht?

2024-01-10 20:16 UTC, Scepzz commented
Die current time läuft weiter wenn das Spiel mit p pausiert wurde, da der Rest vom Spiel pausiert wird sollte die Zeit denke ich auch pausiert werden.

2024-01-10 21:08 UTC, MatteoXAntoz commented on app/src/main/java/Constants.java
> +    //3 Multiplayerr
Das habe ich mir als Notiz gemacht fuer den Multiplayermodus, loesche es danach :)

2024-01-10 21:09 UTC, MatteoXAntoz commented on app/src/main/java/Game.java
> +double bounce;
Jein, wir muessen gucken, wie wir es machen. 
Wir braeuchten noch eine Methode fuer den Multiplayermodus, man koennte beide lokal speichern oder eine global.

2024-01-10 21:12 UTC, MatteoXAntoz commented on app/src/main/java/Game.java
> +            DrawTexture(texture, player.x, (int) (player.y+bounce), WHITE);
Geht nicht.
der bounce wert ist eine kommazahl, wenn ich die variable nicht caste dann wird alles mit 0 multipliziert.

2024-01-10 21:12 UTC, MatteoXAntoz commented on app/src/main/java/Stats.java
> +        } else if (round > 1) {
Ja hab es eh komplett umgeaendert.

2024-01-10 21:13 UTC, MatteoXAntoz commented on app/src/main/java/Game.java
> +         // Here will be played all sounds
was schlaegst du vor?
Finde die Aussage passend.

2024-01-10 21:24 UTC, Minerder commented on app/src/main/java/Game.java
> +            DrawTexture(texture, player.x, (int) (player.y+bounce), WHITE);
Oh stimmt habe ich übersehen

2024-01-10 21:51 UTC, Minerder commented on app/src/main/java/Game.java
> +         // Here will be played all sounds
Besser wäre ``Here all sounds will be played`` oder ``All sounds are played here``

2024-01-11 08:12 UTC, MatteoXAntoz commented on app/src/main/java/Game.java
> +       // sounds.add(new Sound(Constants.SOUNDSPATH,"racer"));
das habe ich gemacht, weil es nervig war XD, ist aber wieder da.

2024-01-11 08:13 UTC, MatteoXAntoz commented on app/src/main/java/Stats.java
> +        startTime = end();
wollte es moeglichst wie beim javaScript Code haben, kann ich aber machen.

2024-01-11 08:21 UTC, MatteoXAntoz commented
Aenderungen wurden durchgefuehrt. Werde es mergen.

2024-01-11 08:22 UTC, merged